collections:
  posts:
    output: true
    permalink: /news/:year-:month-:day-:title/
  features:
    output: true
  clients:
    output: true

defaults:
  - scope:
      path: ""
      type: "features"
    values:
      layout: "feature"
  - scope:
      path: ""
      type: "clients"
    values:
      layout: "client"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

permalink: /:title/

plugins:
  - jekyll-mentions

exclude: [vendor, "pages/embed.html", "Gemfile", "Gemfile.lock", "CONTRIBUTING.md", "LICENSE", "README.md"]
include: ["_js"]

strict_front_matter: true

#incremental: true
